version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10

  - package-ecosystem: "ruby:bundler"
    directory: "/"
    schedule:
      interval: "daily"
      bundler
