opt_in_rules:
  - empty_count
included:
  - Sources
  - Tests
excluded:
  - Carthage
line_length: 
  warning: 250 
  error: 500 
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 3
  max_length: 50
identifier_name:
  excluded:
    - id