files:

  - source: /Sources/Localization/en.lproj/Localizable.strings
    translation: /Sources/Localization/%two_letters_code%.lproj/Localizable.strings
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
  - source: /fastlane/metadata/en-US/description.txt
    translation: /fastlane/metadata/%two_letters_code%/description.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
  - source: /fastlane/metadata/en-US/keywords.txt
    translation: /fastlane/metadata/%two_letters_code%/keywords.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/marketing_url.txt
    translation: /fastlane/metadata/%two_letters_code%/marketing_url.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/name.txt
    translation: /fastlane/metadata/%two_letters_code%/name.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/privacy_url.txt
    translation: /fastlane/metadata/%two_letters_code%/privacy_url.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/release_notes.txt
    translation: /fastlane/metadata/%two_letters_code%/release_notes.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/support_url.txt
    translation: /fastlane/metadata/%two_letters_code%/support_url.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK

  - source: /fastlane/metadata/en-US/promotional_text.txt
    translation: /fastlane/metadata/%two_letters_code%/promotional_text.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK

  - source: /fastlane/metadata/en-US/subtitle.txt
    translation: /fastlane/metadata/%two_letters_code%/subtitle.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
        
  - source: /fastlane/metadata/en-US/screenshots_text.txt
    translation: /fastlane/metadata/%two_letters_code%/screenshots_text.txt
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        pt-PT: pt-PT
        nl-BE: nl-BE
        nl: nl
        sr-CS: sr_Latn
        sr: sr_Cyrl
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        zh-HK: zh-HK
