files:
  - source: /xliff/en.xliff
    translation: /xliff/%two_letters_code%.xliff
    
  - source: /Sources/en.lproj/Localizable.strings
    translation: /Sources/%two_letters_code%.lproj/Localizable.strings
    
  - source: /fastlane/metadata/en-US/description.txt
    translation: /fastlane/metadata/%two_letters_code%/description.txt

  - source: /fastlane/metadata/en-US/keywords.txt
    translation: /fastlane/metadata/%two_letters_code%/keywords.txt

  - source: /fastlane/metadata/en-US/marketing_url.txt
    translation: /fastlane/metadata/%two_letters_code%/marketing_url.txt

  - source: /fastlane/metadata/en-US/name.txt
    translation: /fastlane/metadata/%two_letters_code%/name.txt

  - source: /fastlane/metadata/en-US/privacy_url.txt
    translation: /fastlane/metadata/%two_letters_code%/privacy_url.txt

  - source: /fastlane/metadata/en-US/release_notes.txt
    translation: /fastlane/metadata/%two_letters_code%/release_notes.txt

  - source: /fastlane/metadata/en-US/support_url.txt
    translation: /fastlane/metadata/%two_letters_code%/support_url.txt
