# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane'
gem 'xcode-install'
gem 'versionomy'

eval_gemfile("./fastlane/Pluginfile")
