name: OpenFoodFacts

fileGroups: [Cartfile, CONTRIBUTING.md, crowdin.yml, fastlane, ISSUE_TEMPLATE.md, LICENSE, project.yml, PULL_REQUEST_TEMPLATE.md, README.md, Snapshots, scripts, .swiftlint.yml, .gitignore]

options:
  minimumXcodeGenVersion: 2.14.0
  bundleIdPrefix: org.openfoodfacts
  transitivelyLinkDependencies: true
  deploymentTarget: 
    iOS: "10.0"

settingGroups:
  testing-endpoints:
    GET_ENDPOINT: "http:/$()/localhost:8080"
    POST_ENDPOINT: "http:/$()/localhost:8080"
    LOGIN_ENDPOINT: "http:/$()/localhost:8080/cgi/session.pl"
    ROBOTOFF_ENDPOINT: "https:/$()/localhost:8080"
  release-endpoints:
    GET_ENDPOINT: "https:/$()/ssl-api.openfoodfacts.org"
    POST_ENDPOINT: "https:/$()/ssl-api.openfoodfacts.org"
    LOGIN_ENDPOINT: "https:/$()/world.openfoodfacts.org/cgi/session.pl"
    ROBOTOFF_ENDPOINT: "https:/$()/robotoff.openfoodfacts.org"

settings:
  base:
    SWIFT_VERSION: 5
    CODE_SIGN_IDENTITY: iPhone Developer
  configs:
    Debug:
      groups:
        - testing-endpoints
    Release:
      groups:
        - release-endpoints

targets:
  OpenFoodFacts: 
    type: application
    platform: iOS
    sources: 
      - path: Sources
        excludes: 
          - Frameworks/*
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: org.openfoodfacts.scanner
        MARKETING_VERSION: 3.3
        CURRENT_PROJECT_VERSION: 44
        DEVELOPMENT_TEAM: ZC9CYWD334
    dependencies:
      - sdk: MobileCoreServices.framework
      - sdk: AVFoundation.framework
      - framework: Carthage/Build/Alamofire.xcframework
      - framework: Carthage/Build/AlamofireImage.xcframework
      - framework: Carthage/Build/AlamofireObjectMapper.xcframework
      - framework: Carthage/Build/BLTNBoard.xcframework
      - framework: Carthage/Build/Cartography.xcframework
      - framework: Carthage/Build/FloatingPanel.xcframework
      - framework: Carthage/Build/IBLocalizable.xcframework
      - framework: Carthage/Build/ImageViewer.xcframework
      - framework: Carthage/Build/IQKeyboardManagerSwift.xcframework
      - framework: Carthage/Build/KeychainAccess.xcframework
      - framework: Carthage/Build/Kingfisher.xcframework
      - framework: Carthage/Build/MarqueeLabel.xcframework
      - framework: Carthage/Build/NotificationBanner.xcframework
      - framework: Carthage/Build/ObjcExceptionBridging.xcframework
      - framework: Carthage/Build/ObjectMapper.xcframework
      - framework: Carthage/Build/Realm.xcframework
      - framework: Carthage/Build/RealmSwift.xcframework
      - framework: Carthage/Build/Sentry.xcframework
      - framework: Carthage/Build/SnapKit.xcframework
      - framework: Carthage/Build/SVProgressHUD.xcframework
      - framework: Carthage/Build/TOCropViewController.xcframework
      - framework: Carthage/Build/XCGLogger.xcframework
      - framework: Carthage/Build/XLPagerTabStrip.xcframework
      - framework: Carthage/Build/Zip.xcframework

    preBuildScripts:
      - script: |
          if which swiftlint >/dev/null; then
              swiftlint
          else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: SwiftLint

  OpenFoodFactsTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - path: Tests
      - path: TestResources
    dependencies:
      - target: OpenFoodFacts
      - framework: Carthage/Build/Nimble.xcframework
      - framework: Carthage/Build/Quick.xcframework
      - framework: Carthage/Build/OHHTTPStubs.xcframework
  
  OpenFoodFactsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - path: UITests
      - path: TestResources
      - path: Sources/Helpers/AccessibilityIdentifiers.swift
    dependencies:
      - target: OpenFoodFacts
      - framework: Carthage/Build/Swifter.xcframework

  OpenFoodFactsSnapshots:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Snapshots
      - path: Sources/Helpers/AccessibilityIdentifiers.swift
    dependencies:
      - target: OpenFoodFacts
  
schemes:
  OpenFoodFacts:
    build:
      targets:
        OpenFoodFacts: all
    test:
      gatherCoverageData: true
      targets: 
        - name: OpenFoodFactsTests
          randomExecutionOrder: true
        - name: OpenFoodFactsUITests
          randomExecutionOrder: true
        - name: OpenFoodFactsSnapshots
          randomExecutionOrder: true

  OpenFoodFactsTests:
    build:
      targets:
        OpenFoodFactsTests: all
    test:
      gatherCoverageData: true
      targets: 
        - name: OpenFoodFactsTests
          randomExecutionOrder: true

  OpenFoodFactsUITests:
    build:
      targets:
        OpenFoodFactsUITests: all
    test:
      gatherCoverageData: true
      targets:
        - name: OpenFoodFactsUITests
          randomExecutionOrder: true

  OpenFoodFactsSnapshots:
    build:
      targets:
        OpenFoodFactsSnapshots: all
    test:
      gatherCoverageData: true
      targets: 
        - name: OpenFoodFactsSnapshots
          randomExecutionOrder: true
