setup_travis

fastlane_version "1.109.0"

default_platform :ios

desc "Run all the tests"
lane :test do
  sh("defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool no")
  scan(
    scheme: "OpenFoodFacts",
    devices: ["iPhone 8"],
    output_types: "html"
  )
  sh("defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool yes")
end

desc "Build and send the beta to TestFlight"
lane :beta do
  ensure_git_status_clean

  increment_build_number

  match(type: "appstore")

  # build your iOS app
  gym(
    scheme: "OpenFoodFacts"
  )

  test

  # Upload to test flight
  pilot(skip_waiting_for_build_processing: true)

  # Commit version bump
  version = get_version_number(xcodeproj: "OpenFoodFacts.xcodeproj")
  build_number = get_build_number(xcodeproj: "OpenFoodFacts.xcodeproj")
  version_tag = "#{version}-#{build_number}"

  commit_version_bump(
    message: "Version bump to #{version_tag}",
    xcodeproj: "OpenFoodFacts.xcodeproj"
  )
  add_git_tag(
    tag: version_tag
  )
  push_to_git_remote
end
