
name: Finalize Sentry release

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  finalize-sentry-release:
    name: Finalize Sentry release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Decrypt AuthKey file
        run: cd ./fastlane/envfiles && ./decrypt_secrets.sh
        env:
          AUTH_KEY_FILE_DECRYPTKEY: ${{ secrets.AUTH_KEY_FILE_DECRYPTKEY }}

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: 2.6.x

      - name: Install sentry-cli
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: Run Fastlane finalize_sentry lane
        run: bundle exec fastlane finalize_sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SPACESHIP_CONNECT_API_KEY_FILEPATH: envfiles/AuthKey_KDAUTTM76R.p8
          CI_RELEASE: true

