 name: Run release-please
 on:
   push:
     branches:
       - disable-develop
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
